# Generated by Django 5.1.3 on 2024-12-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='standard',
        ),
    ]
